name: Build APK

on:
  push:
    branches:
      - main-alpha
  pull_request:
    branches:
      - main-alpha
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Displays kernel version, hostname, and system architecture.
        run: uname -a

      - name: Shows Linux distribution details
        run: lsb_release -a
    
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3          

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Build with Gradle Debug
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
