name: Build APK On Windows

on:
  push:
    branches:
      - main-beta
  pull_request:
    branches:
      - main-beta
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check Windows System Information
        run: systeminfo

      - name: Get General System Information
        run: Get-ComputerInfo

      - name: Get OS Details
        run: Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, BuildNumber, OSArchitecture
    
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3          

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Build with Gradle Debug
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
