name: Build with the Wrapper On Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Displays kernel version, hostname, and system architecture.
        run: uname -a

      - name: Detailed CPU architecture info
        run: lscpu

      - name: Shows Linux distribution details
        run: lsb_release -a

      - name: Shows Linux distribution details 2
        run: cat /etc/os-release
    
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Build with Gradle Wrapper
        run: ./gradlew build
