name: Build with the Wrapper 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Check Mac Specification
        run: system_profiler SPHardwareDataType

      - name: Check Mac System Software
        run: system_profiler SPSoftwareDataType
    
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Build with Gradle Wrapper
        run: ./gradlew build
